name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync  # If you use a different command like 'uv pip install -r requirements.txt', replace this line!

      - name: Run migrations
        run: uv run python manage.py migrate
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}